### ISSUE TITLE
Better packaging/devops

### ISSUE THREAD

**Issue by jpivarski** [HSF/PyHEP.dev-workshops#1]
Distributing software more reliably to users and maintaining stability while encouraging contributions.

**Comment by gordonwatts** [comment]
I'm not so much interested here, but I often wonder if there is an easy way to build this infrastructure into a package - like a template that one could "just start with" that includes easy documentation, etc.

**Comment by jpivarski** [comment]
So here's a concrete way to frame it: is https://github.com/scientific-python/cookie sufficient? If it's lacking anything, what is it lacking?

**Comment by sudo-panda** [comment]
This is something that we are going to have to face pretty soon with cppyy on top of CppInterOp. 

cc: @vgvassilev

**Comment by ph-ilten** [comment]
+1 From the `Pythia8` side of things packaging is often times taken care of for us by external interested parties. I would very much like to learn about things we can do help facilitate packaging.

**Comment by kjvbrt** [comment]
At FCC we combine analyzer functions written in C++ for the RDataFrame with Python scripting around it. The FCCAnalyses is distributed through Spack package and GitHub repo. I would like to investigate distribution possibilities which keep door open for heavy user customizations.

**Comment by oshadura** [comment]
+1

**Comment by henryiii** [comment]
+1
