### ISSUE TITLE
Dedicated discussion about IRIS-HEP Analysis Grand Challenge

### ISSUE THREAD

**Issue by oshadura** [HSF/PyHEP.dev-workshops#11]
cc: @alexander-held 

- Discussion about the Analysis Grand Challenge (AGC) pipeline and related tools used in the AGC pipeline
- Discussions about the workflow management and preservation pipelines for AGC
- The experience adapting awkward-dask in AGC
-  and many more...

The idea is to have a dedicated discussion possibly on Thursday afternoon (27 July).

Please let us know who is interested to join!

Also don't forget to join us for AGC **hybrid** demonstration event: https://indico.cern.ch/event/1291680

**Comment by oshadura** [comment]
@lgray @nsmith @Moelf @masonproffitt @gordonwatts @matthewfeickert @lukasheinrich @eguiraud @ekauffma please leave here  +1  if you would be interested to participate (for people who can't join us  in person, we will try to organise ZOOM connection in one of rooms)

**Comment by lgray** [comment]
+1

**Comment by eguiraud** [comment]
Hi, I will be busy half of the day, but I don't know which half yet :/ I'll connect remotely if I can!

**Comment by Moelf** [comment]
+1

**Comment by masonproffitt** [comment]
+1

**Comment by gordonwatts** [comment]
+1

**Comment by ekauffma** [comment]
+1

**Comment by matthewfeickert** [comment]
+1

**Comment by riga** [comment]
+1

**Comment by riga** [comment]
+1
