### ISSUE TITLE
Analysis organizational principles in practice: dask / luigi and the line in the sand between the two

### ISSUE THREAD

**Issue by lgray** [HSF/PyHEP.dev-workshops#18]
Dask and Luigi (and their contemporaries) are both extremely flexible tools that provide ways to generate DAGs. Dask is often well situated to describe the data-flow and mathematical operations on some inputs, and Luigi is engineered more to isolate and interlink larger conceptual chunks of "stuff to do" into a complete workflow. Either can achieve the functionality of the other, but it's clear there's some boundary using *both* which achieves a clean and focusing division of responsibilities. 

Let's talk about it. :-)

**Comment by maxgalli** [comment]
+1

**Comment by btovar** [comment]
+1

**Comment by pfackeldey** [comment]
+1

**Comment by alexander-held** [comment]
+1

**Comment by mattbellis** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by jonas-eschle** [comment]
That's interesting! Maybe we can also bring snakemake into the game? It's used a lot in LHCb at least

**Comment by nsmith-** [comment]
+1

**Comment by riga** [comment]
+11

**Comment by oshadura** [comment]
+1
