### ISSUE TITLE
Fitting tools, combined fits, partial wave analysis, and machine learning

### ISSUE THREAD

**Issue by jpivarski** [HSF/PyHEP.dev-workshops#5]
Extracting statistical results from data with systematics, correlations, etc. at large scale.

**Comment by maxgalli** [comment]
Interested in this topic! I'm mostly interested in investigating interoperability between Combine (tool that is still used in CMS to perform combinations and fits pretty much in every analysis) and modern packages (pyhf, cabinetry, zfit, etc.).

**Comment by rkansal47** [comment]
Also interested in discussing Python-based alternatives to Combine!

**Comment by lgray** [comment]
jaxfit @nsmith-

**Comment by vgvassilev** [comment]
I am interested in adopting the work we did in RooFit and AD in Combine. 

cc: @grimmmyshini, @guitargeek, @sudo-panda, @davidlange6

**Comment by pfackeldey** [comment]
+1

**Comment by ccochato** [comment]
+1

**Comment by alexander-held** [comment]
I'm also interested in this. Another aspect to this topic is orchestration of model construction / metadata handling, which ties in with earlier steps in an analysis workflow. Regarding AD: also curious to learn more about how / how much of the functionality is exposed to users (i.e. can I easily take arbitrary derivatives myself, how limited are current implementations to just internally provide derivatives wrt. parameters to the minimizer).

@redeboer: probably best to open a new issue as this might get lost here and is not related to the thread. Presumably interesting e.g. for [scikit-hep/particle](https://github.com/scikit-hep/particle).

**Comment by alexander-held** [comment]
> General question: what do we mean by ML under the heading of "fitting"?

One thing that fits into that box is simulation-based inference à la e.g. [MadMiner](https://github.com/madminer-tool/madminer) or various anomaly detection methods.

**Comment by phinate** [comment]
can't attend in-person sadly but would love to be involved in any discussions here if possible (timezones permitting)!

**Comment by nsmith-** [comment]
I'm very interested in a jax-based statistical inference package, towards both binned and un-binned fits.
- @redeboer I only have thought about sympy-assisted model building but glad to see you've made real progress there!
- I'll +1 the HEP Statistics Serialization Standard HS3 as a topic worth discussing.
- Perhaps it is time to revitalize https://github.com/scikit-hep/pyhf/issues/608 towards a common statistical _interpretation_ API (evolution of RooStats, say), as this plus a serialization standard allows to switch out backends as necessary for performance.

**Comment by phinate** [comment]
> I'm very interested in a jax-based statistical inference package, towards both binned and un-binned fits.

Is this better-scoped as a statistical *modelling* package, where one would find the appropriate abstraction that fits both binned/unbinned paradigms? Inference would just be extra layers on minimization, which I've already abstracted in [`relaxed`](https://github.com/gradhep/relaxed/blob/main/src/relaxed/infer.py) for the most common cases encountered in `pyhf` (profile likelihood-based testing) -- the only important API requirement is the existence of the `.logpdf` method. (Upper limits are a small extension over that with a root-finder).

**Comment by phinate** [comment]
> @phinate yes! I guess your `relaxed` is an implementation of https://github.com/scikit-hep/pyhf/issues/608 ?

oh, I suppose so in a not-well-tested kind of way :) just asymptotic calcs though, and probably needs a quick going-through to truly be agnostic to the model representation but it is just a thin wrapper around jaxopt with HEP-like quantities/semantics!

would be happy to build this out more to support whatever model abstraction we can come up with!

**Comment by redeboer** [comment]
> We need to address the readability of these codes and work towards creating user-level code that interfaces with the base code. Again, I bring up GooFit as an example - it does a great job of shielding the user from the intricacies of CUDA code to perform an analysis. Despite this, I find that there's room for improvement in the user experience, and I believe it would be fruitful for us to discuss these issues during the workshop.

I fully agree!

Is it an idea to organise a dedicated session for amplitude analysis (UX and documentation specifically)? If so, who would be interested? @JMolinaHN @mdsokoloff @jonas-eschle?

**Comment by JMolinaHN** [comment]
@redeboer of course a discussion on amplitude analysis would be more than interesting! (in view of the latest results, I think we need it). From my point of view, I refuse to think that it can't be done a likelihood analysis in some decays like Dpipipi or Dkpipi. We all know those decays are challenging because of the pipi (in general, pp) but in some sense we should be adecuate (sensitive) to problems like that.

**Comment by mattbellis** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by nikoladze** [comment]
+1

**Comment by jonas-eschle** [comment]
> > I'm very interested in a jax-based statistical inference package, towards both binned and un-binned fits.
> 
> @nsmith- Is this better-scoped as a statistical _modelling_ package, where one would find the appropriate abstraction that fits both binned/unbinned paradigms? Inference would just be extra layers on minimization, which I've already abstracted in [`relaxed`](https://github.com/gradhep/relaxed/blob/main/src/relaxed/infer.py?rgh-link-date=2023-07-10T14%3A55%3A01Z) for the most common cases encountered in `pyhf` (profile likelihood-based testing) -- the only important API requirement is the existence of the `.logpdf` method. (Upper limits are a small extension over that with a root-finder).

This is basically what zfit already solves, it combines binned and unbinned (and mixed) fits. I think it's crucially more than relaxed, which allows to use histogram templates as an unbinned PDF (afaiu), but there is more to that: analytic shapes, numerical integration & sampling methods, arbitrary correlations etc.

I also agree with the others, to point the three main topics that I see:
- fitting tools landscape and interface (how to define an interface for a distribution, parameters etc). There are a lot around but all with their purpose and the main goal should be to bring them closer together
- backends: Sympy and JAX are some popular ones, but they're not without drawbacks (i.e. TensorFlow is partially more powerful than JAX, there is [aesara](https://aesara.readthedocs.io/en/latest/introduction.html) (and ping to @redeboer ;) ) that improves Sympy expressions). How can all of these work together best?
- statistical language and serialization standard ([HS3](https://github.com/hep-statistics-serialization-standard/hep-statistics-serialization-standard), decaylanguage, pyhf histfactory json) to have a common format of serializing (and publishing/exchanging!) likelihoods and models, also Amplitude fit models.

**Comment by nsmith-** [comment]
> zfit already solves, it combines binned and unbinned (and mixed) fits

In this regard, zfit and RooFit are alone at the moment. What I would like to understand is how their representations of mixed binned-unbinned data compare/contrast.

As an aside, Combine also can produce unbinned "pseudo-Asimov" datasets to take advantage of asymptotic methods. Is this something done elsewhere? (I am just ignorant here)

> TensorFlow is partially more powerful than JAX

Curious about this!

**Comment by alexander-held** [comment]
> As an aside, Combine also can produce unbinned "pseudo-Asimov" datasets to take advantage of asymptotic methods.

@nsmith- I'm curious to learn more about this. Is this in the docs?

**Comment by nsmith-** [comment]
There is a brief discussion here http://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/part3/runningthetool/#asimov-datasets

**Comment by matthewfeickert** [comment]
This topic seems perhaps too broad, and while I expect that during the week it will split out across different areas organically the areas that I think I'm most probable to spend time discussing are:

* Moving towards tools accepting and revising [HS3](https://github.com/hep-statistics-serialization-standard/hep-statistics-serialization-standard). :heavy_check_mark: 
   - There has already been a great deal of work done by people here (not me as I dropped the ball on this early in 2023 &mdash; sorry all) and I think making some headway here in addition to the meetings that have happened would be useful.
* Along the lines of standards, having tools in the Pythonic fitting space look at the [Array API](https://data-apis.org/) and use of `array-api-compat`
   - c.f. https://github.com/scikit-hep/pyhf/issues/2253
   - c.f. Aaron Meurer's SciPy 2023 talk: [Python Array API Standard: Toward Array Interoperability in the Scientific Python Ecosystem](https://github.com/data-apis/scipy-2023-presentation/blob/main/presentation/Slides.pdf)
* #27
